version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
